### ISSUE TITLE
When open the app, it says "Currently not available"

### ISSUE THREAD

**Issue by pnplusplus** [iusmac/RevampedFMRadio#1]
As the title suggest, i've build a rom with RevampedFMRadio bundled. I've follow the tutorial steps too. But when i open the fm radio app, its says "Currently not available". Here the screenshot and some logs that i take.

Do you know how to fix it?
[fmradio.txt](https://github.com/iusmac/RevampedFMRadio/files/10334779/fmradio.txt)
![Screenshot_20230103-065200_FM Radio](https://user-images.githubusercontent.com/52704636/210313541-14822936-2482-46c5-996a-9137db3c0266.png)

**Comment by iusmac** [comment]
The error is:
```
E android_hardware_fm: open_dev failed, [fd=-1] /dev/radio0
```
It means that the JNI library cannot establish communication with your kernel driver. Ensure the `/dev/radio0` path exists. If yes, then check if your init scripts can properly init the FM driver when `hw.fm.init` prop is set:
https://github.com/iusmac/device_rova/blob/25247a2ea9019305312a4e88aaa81a39c612bff3/rootdir/etc/init.qcom.rc#L411-L412

And the perms to allow writing to sysfs node:
https://github.com/iusmac/device_rova/blob/25247a2ea9019305312a4e88aaa81a39c612bff3/rootdir/etc/init.qcom.rc#L125
https://github.com/iusmac/device_rova/blob/25247a2ea9019305312a4e88aaa81a39c612bff3/rootdir/etc/init.qcom.rc#L128

p.s if your're rooted, you can directly try this via terminal and restart the FM app:
```bash
echo 1 > /sys/module/radio_iris_transport/parameters/fmsmd_set
```

**Comment by pnplusplus** [comment]
Ah, okay, thanks for your hints. I dont have `hw.fm.init` on my .prop too, maybe i should add it right?

**Comment by iusmac** [comment]
Set it to `0` ofc.

**Comment by pnplusplus** [comment]
One more thing, i see your `/dev/radio0` is set to `0666` right?

**Comment by iusmac** [comment]
```python
# ueventd.qcom.rc
/dev/radio0    0666   system    system
```

**Comment by pnplusplus** [comment]
Thank you so much for your help and great software anyways.
