### ISSUE TITLE
FM - Force close

### ISSUE THREAD

**Issue by TogoFire** [iusmac/RevampedFMRadio#2]
I followed the instructions, but here it is closing and opening and when it decides to stay open, it doesn't work when I press play.

Log crash: https://katb.in/sekozuvogup
Logcat: https://katb.in/tomadekiniz

DT/VT/KT - FM commmits:
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/aacc49bae838f8fafb32629e84a209d4d985ec08
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/91d9a16e78d0d0b461f09fa0e3a0874c50e3e192
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/f4842535433310171f2a234288c704065072c724
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/blob/1f6849e7d218a1c3bef7489e18192d728d2c2e0d/prop.mk#L156
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/blob/1f6849e7d218a1c3bef7489e18192d728d2c2e0d/BoardConfig.mk#L129
https://github.com/iusmac/device_rova/blob/7a8f67877692e09490c70dfaffd3ac5d12a903e8/device.mk#L164
https://github.com/Dev-msm8953/android_vendor_xiaomi_daisy/commit/82e475fd184361431b18cdebd060176d8c1b3518
https://github.com/Dev-msm8953/android_vendor_xiaomi_daisy/blob/82e475fd184361431b18cdebd060176d8c1b3518/msm8953-common/msm8953-common-vendor.mk#L119
https://github.com/Dev-msm8953/kernel_xiaomi_msm8953/commit/bda9326e4cbd79c5d14c981ac0d2b004c6ab7625
https://github.com/Dev-msm8953/audio_kernel_techpack/commit/e4df13ab14a5ccf8a01fa371a6fe51d3cc763393

Am I forgetting something?

**Comment by iusmac** [comment]
> https://github.com/Dev-msm8953/android_device_xiaomi_daisy/blob/1f6849e7d218a1c3bef7489e18192d728d2c2e0d/BoardConfig.mk#L129

This is a dead prop.

There's other important prop which you have by default:
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/blob/1f6849e7d218a1c3bef7489e18192d728d2c2e0d/BoardConfig.mk#L130
If set, the FM driver is started by setting the prop `hw.fm.init` = `1`
https://github.com/iusmac/RevampedFMRadio/blob/5125eeab07fd83f7dbf0641a1aea68b816cbb76a/jni/FM_Const.h#L123-L127
I wasn't able to find this rule in your init.rc scripts, you probably didn't reverted some newer commits that removed this rule and related node perms. This was already mentioned in https://github.com/iusmac/RevampedFMRadio/issues/1#issuecomment-1369595917.

**Comment by TogoFire** [comment]
Ok. I will test here now.

**Comment by TogoFire** [comment]
Commits:
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/1308c2ac6acb7ca37dbb9b8dca524d78c5ea5340
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/5c7aa4c4401640604ad2b0bded00152fbfa4be85
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/d8cd91ebaa9635965fe0dacac2364257f57f0134
https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/b40f17e7f36ec46dfb8dda65a21c2224b5a80492

I tested the commits you mentioned, it almost worked, but without success. Still force close, but less. It almost wanted to work, but it didn't, tracks don't skip and still no audio.

Log crash: https://katb.in/ahidoludodi
Logcat: https://katb.in/ipecahaveqa

Image: https://prnt.sc/5qdU3Az6uHpR

**Comment by iusmac** [comment]
> Dev-msm8953/android_device_xiaomi_daisy@b40f17e

This doesn't make any sense. Please, read what I wrote about `TARGET_QCOM_NO_FM_FIRMWARE` prop.

**Comment by TogoFire** [comment]
> > [Dev-msm8953/android_device_xiaomi_daisy@b40f17e](https://github.com/Dev-msm8953/android_device_xiaomi_daisy/commit/b40f17e)
> 
> This doesn't make any sense. Please, read what I wrote about `TARGET_QCOM_NO_FM_FIRMWARE` prop.

I had to use this to not get all white and no numbers. And the app doesn't stay open for a long time if I remove it. I will try more here.

Image: https://prnt.sc/Hi3D5g0xcm-N

**Comment by iusmac** [comment]
No need to guess the issue, just bring back all the functionality needed for the stock FMRadio from LOS 18.1. If it will work then this will work too. Just pay attention to the reverted commits, as It's strange to me why some basic QCOM stuff like `hw.fm.init` prop rule is missing in your init.rc scripts...

**Comment by TogoFire** [comment]
I looked at my old android 11 tree that was ok the fm-lineage, and other trees, I undo some reverts that I had done that I didn't need, props and permissions. And in the end nothing makes sense not to have worked. So then I try that soon. For now I'm going to use caf fm which is ok here.
Thanks for listening.
