### ISSUE TITLE
I have no vendor.prop

### ISSUE THREAD

**Issue by thebestofall007** [iusmac/RevampedFMRadio#4]
How do I install this if my build doesn't have a vendor.prop file? Did you mean the build.prop file in the vendor partition? I know how to install it until I get to steps 4 and 5 in the qcom section, then I'm lost.

**Comment by iusmac** [comment]
Conventionally it's called `vendor.prop` and is defined in device tree like this

`TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop`

Then, it's copied to `/vendor/build.prop`. There's also `system.prop` that goes to `/system/build.prop`. Same for `system_ext.prop` and `product.prop` that have their corresponding partition.

**Comment by thebestofall007** [comment]
mine is a little bit different. it says "TARGET_VENDOR_PROP += device/motorola/borneo/props/vendor.prop" in the device.mk

**Comment by thebestofall007** [comment]
I'm now stuck on step 5. Where does the string "# sepolicy/vendor/system_app.te
get_prop(system_app, vendor_bluetooth_prop)" go?

**Comment by iusmac** [comment]
Create the `system_app.te` file here https://github.com/thebestofall007/android_device_motorola_borneo-1/tree/lineage-18.1/sepolicy/vendor (or whatever your device tree is) and place `get_prop(system_app, vendor_bluetooth_prop)` inside it.

**Comment by thebestofall007** [comment]
my device tree actually is from the moto-common project by electimon, but anyways, the app launches, but I get "currently not available".

**Comment by iusmac** [comment]
This is the part where the maintainer has to do some work with their device/kernel/vendor tree. There're already some closed issues about FM service unavailability. Check them out. #1 #2 

I'm locking the issue as the topic has been fully exhausted.
