### ISSUE TITLE
Standalone apk?

### ISSUE THREAD

**Issue by dgudim** [iusmac/RevampedFMRadio#5]
Is it possible to build a standalone apk that can be installed on a stock rom?

**Comment by iusmac** [comment]
No for various reasons, but the most obvious one is the cert mismatch. Stock ROM vendors sign the ROM and built-in apps with their own private key. As this is a system app, you must sign it with stock ROM keys, which you can't have.

**Comment by dgudim** [comment]
Well, that's unfortunate. Thanks for explaining
