### ISSUE TITLE
Didn't work 

### ISSUE THREAD

**Issue by spiral009** [iusmac/RevampedFMRadio#6]
Logcat 
[fmradio.txt](https://github.com/iusmac/RevampedFMRadio/files/13430713/fmradio.txt)
I did everything mentioned in #1
Added `hw.fm.init=0` to vendor.prop 
init.qcom.rc didn't have this line so I add it Manually
```
on property:hw.fm.init=*
    write /sys/module/radio_iris_transport/parameters/fmsmd_set ${hw.fm.init}
```
The other two chmod were there
Then I recompiled the Kernel with IRIS radio flag to get this file ```/sys/module/radio_iris_transport/parameters/fmsmd_set```
I couldn't find ```sepolicy/vendor/system_app.te```
So I added the line 
```
get_prop(system_app, vendor_bluetooth_prop)
```
To another system_app.te file

I noticed this in the log 
```
android_hardware_fm: open_dev failed, [fd=-1] /dev/radio0[0m
```
But I have it set properly I think
```
.../files/home # ls -alth /dev/radio0                                            crw-r----- 1 system system 81, 64 Aug 19  1971 /dev/radio0
```

**Comment by spiral009** [comment]
Different log here
I also noticed iris directory is empty 
```
.../files/home # ls /sys/module/radio_iris_transport
parameters  uevent
.../files/home # ls /sys/module/radio_iris_transport/parameters/              
   fmsmd_set                                                                        .../files/home #
```
[fmradio.txt](https://github.com/iusmac/RevampedFMRadio/files/13449656/fmradio.txt)

**Comment by iusmac** [comment]
It's not empty. The driver is exposing its interface via `fmsmd_set` param file, allowing you to enable or disable it, that's all. It isn't supposed to do anything else. The main question is why this driver was disabled in the kernel config? Are you sure your device has FM radio capabilities?

**Comment by spiral009** [comment]
> It's not empty. The driver is exposing its interface via `fmsmd_set` param file, allowing you to enable or disable it, that's all. It isn't supposed to do anything else. The main question is why this driver was disabled in the kernel config? Are you sure your device has FM radio capabilities?

Well it's a realme GT Neo 2 , it doesn't have a headphone jack so yeah maybe

**Comment by iusmac** [comment]
There's pretty much no way you can get the FM radio signal without support for wired earphones/headphones used as an antenna. Most local FM radio stations can be listened to wirelessly, because there's headphone jack socket used as an antenna, even though it's short, you still have something "metallic" connected to the PCB.

**Comment by seisdr** [comment]
This might be stupid but USB to audio jack?
Also what is the use of /dev/radio0 why is it there when device don't support radio or don't have a headphone jack

**Comment by iusmac** [comment]
Of course not. There's no kernel driver support for this.
