### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ersin3381** [iusmac/RevampedFMRadio#7]
Can you share a ready to use APK file for my mediatek dimensity 1200 cpu 😭

**Comment by USLTD** [comment]
Unfortunately you will need to:
 1. Either build it by yourself
 2. Get built APK and additional library from someone else who has **EXACTLY** same device as you

You are not first to ask for APK and neither will be last.
#3 #5

**Comment by ersin3381** [comment]
I understand and thank you for your attention..
